# Generated by Django 4.1.7 on 2023-04-10 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z][A-Za-z]{1,19})$')])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2023)])),
                ('price', models.IntegerField(blank=True, default=1000)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('updated_add', models.DateTimeField(auto_now=True)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_parks.autoparkmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
