# Generated by Django 4.2 on 2023-04-11 20:44

from django.db import migrations, models

import core.services.uppload_car_services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_photo_alter_carmodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.uppload_car_services.upload_to),
        ),
    ]
