# Generated by Django 4.2 on 2023-04-13 16:42

import django.db.models.deletion
from django.db import migrations, models

import core.services.uppload_car_services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_photo_alter_carmodel_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=core.services.uppload_car_services.upload_to)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carmodel')),
            ],
            options={
                'db_table': 'cars_photo',
            },
        ),
    ]
