# Generated by Django 4.1.7 on 2023-04-10 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MyAutoPark', max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][A-Za-z\\d]{1,29})$')])),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('updated_add', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auto_park',
            },
        ),
    ]
