# Generated by Django 4.1.7 on 2023-04-09 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0002_autoparkmodel_created_add_autoparkmodel_updated_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparkmodel',
            name='name',
            field=models.CharField(default='MyAutoPark', max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z][A-Za-z\\d])$')]),
        ),
    ]
