# Generated by Django 4.2 on 2023-04-11 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparkmodel',
            name='name',
            field=models.CharField(default='MyAutoPark', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,20}$', 'only letters min 2 max 20 ch')]),
        ),
    ]
