# Generated by Django 4.2 on 2023-04-11 20:44

from django.db import migrations, models

import core.services.uppload_users_profile_service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_name_alter_profilemodel_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.uppload_users_profile_service.upload_to),
        ),
    ]
